# Generated by Django 2.1.7 on 2026-02-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20260203_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.VolunteerOpportunity')),
            ],
        ),
    ]
