# Generated by Django 2.1.7 on 2026-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('Money', 'Money'), ('Blood', 'Blood'), ('Items', 'Items')], default='Money', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
